version: "3.7"
services:
  users_db:
    env_file: backend/users/build/db/dev.env
    image: postgres:12
    volumes:
      - users_db:/var/lib/postgresql/data

  users_svc:
    env_file: backend/users/build/svc/dev.env
    build:
      context: backend/users
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: users
    ports:
      - "9990:9990"
    volumes:
      - ./backend/users/migrations:/users/migrations
    depends_on:
      - users_db

  products_db:
    env_file: backend/products/build/db/dev.env
    image: postgres:12
    volumes:
      - products_db:/var/lib/postgresql/data

  products_svc:
    env_file: backend/products/build/svc/dev.env
    build:
      context: backend/products
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: products
    ports:
      - "9992:9992"
    volumes:
      - ./backend/products/migrations:/products/migrations
    depends_on:
      - products_db

  images_svc:
    env_file: backend/images/build/svc/dev.env
    build:
      context: backend/images
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: images
    volumes:
      - ./backend/images/tmp:/images/tmp
      - ./backend/images/tmp_:/tmp
    ports:
      - "9993:9993"

  address_svc:
    env_file: backend/address/build/svc/dev.env
    build:
      context: backend/address
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: address
    ports:
      - "9995:9995"
    volumes:
      - ./backend/address/migrations:/address/migrations
    depends_on:
      - address_db

  services_svc:
    env_file: backend/services/build/svc/dev.env
    build:
      context: backend/services
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: services
    ports:
      - "9994:9994"
    volumes:
      - ./backend/services/migrations:/services/migrations
    depends_on:
      - services_db

  services_db:
    env_file: backend/services/build/db/dev.env
    image: postgres:12
    volumes:
      - services_db:/var/lib/postgresql/data

  address_db:
    env_file: backend/address/build/db/dev.env
    image: postgres:12
    volumes:
      - address_db:/var/lib/postgresql/data

  semantic_db:
    env_file: backend/semantic/build/db/dev.env
    image: postgres:12
    volumes:
      - semantic_db:/var/lib/postgresql/data

  semantic_svc:
    env_file: backend/semantic/build/svc/dev.env
    build:
      context: backend/semantic
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: semantic
    ports:
      - "9991:9991"
    volumes:
      - ./backend/semantic/migrations:/semantic/migrations
    depends_on:
      - semantic_db

  mailer_svc:
    env_file: backend/mailer/build/svc/dev.env
    build:
      context: backend/mailer
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: mailer
    ports:
      - "9901:9901"

  identifier_svc:
    env_file: backend/identifier/build/svc/dev.env
    build:
      context: backend/identifier
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: identifier
    ports:
      - "9902:9902"

  auth_svc:
    env_file: backend/auth/build/svc/dev.env
    build:
      context: backend/auth
      args:
        github_user: ${GITHUB_USER}
        github_token: ${GITHUB_TOKEN}
        svc_name: auth
    ports:
      - "9900:9900"
    depends_on:
      - auth_redis

  auth_redis:
    image: redis:4-alpine
    command: redis-server --requirepass redis_pwd
    volumes:
      - auth_redis:/data

volumes:
  images_svc:
  users_svc:
  users_db:
  products_svc:
  products_db:
  auth_redis:
  semantic_svc:
  semantic_db:
  address_svc:
  address_db:
  services_svc:
  services_db:
